source 'https://rubygems.org'
ruby '2.5.0'

gem 'activeadmin', github: 'activeadmin/activeadmin'
gem 'browser-timezone-rails'
gem 'devise'
gem 'faker', git: 'https://github.com/stympy/faker.git', branch: 'master'
gem 'figaro'
gem 'gon'
gem 'htmltoword'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
gem 'jbuilder', '~> 2.0'
gem 'letter_opener', group: :development
gem 'mail_interceptor', group: [:development, :staging]
gem 'mailjet'
gem 'omniauth-facebook'
gem 'pagy'
gem 'pg', '~> 0.20'
gem 'puma'
gem 'puma_worker_killer'
gem 'pundit'
gem 'rails', '5.0.5'
gem 'redis'
gem 'rubocop', group: :development
gem 'rubocop-performance'
gem 'sitemap_generator'
gem 'words_counted' # https://github.com/abitdodgy/words_counted

gem 'attachinary', github: 'assembler/attachinary'
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'cloudinary', '1.1.7'
gem 'coffee-rails'
gem 'font-awesome-sass', '~> 5.8.1'
gem 'hamburgers'
gem 'jquery-fileupload-rails'
gem 'jquery-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'

group :development, :test do
  gem 'bullet'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
